# start by pulling the python image
FROM python:3.13.3-slim

# switch working directory
WORKDIR /app

COPY requirements.txt /app/

# install the dependencies and packages in the requirements file
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir chunkipy

COPY . /app

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "app.py", "--server.fileWatcherType none", "--server.port=8501", "--server.address=0.0.0.0"]